name: Go

on:
  push:
    branches: [ main ]
    paths_ignore:
      - README.md
      - .gitignore
  pull_request:
    branches: [ main ]
    paths_ignore:
      - README.md
      - .gitignore

jobs:

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
